version: '2'
services:
    backend:
        build: backend/.
        container_name: olx-sac-backend
        volumes:
          - ./backend:/backend
        command: flask run --host=0.0.0.0
        expose:
          - 5000
        ports:
          - 5000:5000
        environment:
            FLASK_APP: run.py
            FLASK_DEBUG: 1
            PORT: 5000
    frontend:
        build: frontend/.
        container_name: olx-sac-frontend
        volumes:
          - ./frontend:/frontend
        expose:
          - 8080
          - 3000
          - 8081
        ports:
          - 3000:3000
        depends_on:
          - backend
        links:
          - backend
        command: npm run start
