.SILENT:
PYTHON=.venv/bin/python
PIP=.venv/bin/pip
PYTEST=.venv/bin/pytest


clean:
	find . \( -name *.py[co] -o -name __pycache__ \) -delete

venv:
	virtualenv .venv --python=python3

setup: venv
	${PIP} install -U pip
	${PIP} install -r requirements.txt

setup-local: setup
	${PIP} install -r requirements_dev.txt

test: clean
	 PYTHONPATH=. ${PYTEST} tests/ -s -r a --color=yes -vvv

test-cov: clean
	PYTHONPATH=. ${PYTEST} tests/ --cov=app -s

run: clean
	PYTHONPATH=. ${PYTHON} run.py
