"""empty message

Revision ID: baaf1ea9406c
Revises: b84d475bb4d5
Create Date: 2017-08-12 21:49:50.065665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baaf1ea9406c'
down_revision = 'b84d475bb4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'country', ['country'])
    op.create_unique_constraint(None, 'reason', ['reason'])
    op.alter_column('record_called', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('record_called', 'reason_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('record_called', 'type_called_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'type_called', ['type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'type_called', type_='unique')
    op.alter_column('record_called', 'type_called_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('record_called', 'reason_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('record_called', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'reason', type_='unique')
    op.drop_constraint(None, 'country', type_='unique')
    # ### end Alembic commands ###
